name: wearver_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'
dependencies: 
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  flutter: 
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  html: ^0.15.4
  http: ^1.1.0
  pubspec_dependency_sorter: ^1.0.4
dev_dependencies: 
  blackfoot_flutter_lint: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
flutter_launcher_icons: 
  image_path_android: assets/wearver_icon.jpg
  image_path_ios: assets/wearver_icon.jpg
  adaptive_icon_background: assets/wearver_icon.jpg
  adaptive_icon_foreground: assets/wearver_icon.jpg
  background_color_ios: '#544A56'
  web: 
    image_path: assets/wearver_icon.jpg
    background_color: '#544A56'
    theme_color: '#544A56'
    generate: true
  windows: 
    image_path: assets/wearver_icon.jpg
    generate: true
    icon_size: 48
  macos: 
    image_path: assets/wearver_icon.jpg
    generate: true
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
flutter: 
  fonts: 
    - 
      family: Font
      fonts: 
        - 
          asset: assets/font.otf
    - 
      family: Apple
      fonts: 
        - 
          asset: assets/apple.otf
    - 
      family: Apple2
      fonts: 
        - 
          asset: assets/apple2.otf
  assets: 
    - assets/
  uses-material-design: true
