on:
  push:
    branches:
      - main

name: Build my App

jobs:
  build:
    name: Build and Release new APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get
        working-directory: ./front
      - name: Build APK
        run: flutter build apk --release --split-per-abi
        working-directory: ./front


      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "front/build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.SECRETS_APK }}
          tag: v0.0.2